#services:
#  db:
#    image: postgres:15.0-alpine
#    environment:
#      POSTGRES_DB: "rfad_databae"
#      POSTGRES_USER: "rfad_user"
#      POSTGRES_PASSWORD: "123qwe"
#    volumes:
#      - postgres_data:/var/lib/postgresql/data/